package methodology

// The research-methodology glossary: the terms used as the columns of the
// document-term matrix in Kosztyán et al. (2025), "Automated research
// methodology classification using machine learning", Engineering Applications
// of Artificial Intelligence 156, 111039, Appendix A, Table A.9.
//
// LICENCE. The source paper is open access under CC BY 4.0, so this list is
// reproduced here with attribution. The authors' code repository
// (github.com/kzst/article_classifier) carries NO licence and is therefore
// all-rights-reserved; nothing from it is used here, and nothing here was
// derived from reading it.
//
// The paper states 307 terms. Its published table repeats eight of them —
// "meta-analysis", "pretest", "standardized" and five more — so there are 301
// distinct. Anyone rebuilding the matrix by counting printed rows would size it
// wrong, which is why the count is stated here rather than left implied.
//
// Held in Go rather than parsed from JSON at run time for the same reason as
// segment's role table: this package is pure domain logic and must stay callable
// with no working directory and no file access. TestGlossaryMatchesTestdata
// proves the two have not drifted.

// glossaryTerms is the full column set, in alphabetical order.
var glossaryTerms = []string{
	"Accuracy",
	"Action Research",
	"Administrative Data",
	"Affective Measure",
	"Aggregate",
	"Alpha Level",
	"ANCOVA",
	"Anonymity",
	"ANOVA",
	"Association",
	"Attrition",
	"Average",
	"Axiom",
	"Behavioral Categories",
	"Bell-Shaped Curve",
	"Benchmarking",
	"Beta Level",
	"Between-Subjects Design",
	"Bias",
	"Bootstrapping",
	"Case Study",
	"Categorical Data",
	"Causal Analysis",
	"Causal Inference",
	"Causal Relationship",
	"Causality",
	"Ceiling",
	"Census",
	"Central Limit Theorem",
	"Central Tendency",
	"Chart",
	"Chi Square",
	"Chi Squared",
	"Closed questions",
	"Cluster Analysis",
	"Coefficient",
	"Cognitive Interviewing",
	"Cohort",
	"Comparability",
	"Composite Reliability",
	"Confidence",
	"Confidentiality",
	"Consistency",
	"Constant",
	"Contamination",
	"Content Analysis",
	"Context Conditionality",
	"Context Sensitivity",
	"Control Group",
	"Controlled Experiment",
	"Controlled Observation",
	"Correlation",
	"Correlational",
	"Counterbalancing",
	"Covariable",
	"Covariance",
	"Covariate",
	"Coverage",
	"Covert Observation",
	"Critical Incident Technique",
	"Cronbach’s Alpha",
	"Cross Tabulation",
	"Cross-Sectional Data",
	"Crossover Design",
	"Curvilinear",
	"Dashboard",
	"Data Analysis",
	"Data Mining",
	"Data Reduction",
	"Deduction",
	"Deductive Method",
	"Degrees of Freedom",
	"Delphi",
	"Dendrogram",
	"Deviation",
	"Discriminant Analysis",
	"Dispersion",
	"Distribution",
	"Double-Barreled Question",
	"Double-Blind",
	"Duration Model",
	"Effect Size",
	"Endogeneity",
	"Engineering Applications",
	"Estimation",
	"Ethnographic Decision Model",
	"Ethnography",
	"Evaluation Apprehension",
	"Event History Analysis",
	"Exogeneity",
	"Experimental Control",
	"Experimental Design",
	"Expert Panel",
	"Expert study",
	"Explanatory Analysis",
	"Exploratory Data Analysis",
	"Exploratory Study",
	"Extrapolation",
	"Factor Analysis",
	"Field experiment",
	"Field Research",
	"Focus Group",
	"Focus Study",
	"Forecasting",
	"Friedman Test",
	"Fuzzy",
	"Game Theory",
	"Generalized Linear Mixed Model",
	"Generalized Linear Model",
	"Grounded Theory",
	"Hawthorne Effect",
	"Heterogeneity",
	"Heteroskedastic",
	"Hierarchical Linear Modeling",
	"Hierarchical Model",
	"Histogram",
	"Hypothesis",
	"Imputed Response",
	"In-depth Interviewing",
	"Independent Group Design",
	"Indicator",
	"Indirect Effect",
	"Inductive Method",
	"Informed consent",
	"Insiderness",
	"Instrument Error",
	"Intent to Treat",
	"Inter-Observer Reliability",
	"Interaction Effect",
	"Intercept",
	"Interrater reliability",
	"Interval",
	"Interview",
	"Jackknife Technique",
	"Kruskal Wallis Test",
	"Kurtosis",
	"Laboratory Experiment",
	"Latent Growth Model",
	"Least Squares",
	"Likert Scale",
	"Link Analysis",
	"Log-Linear Analysis",
	"Logit Model",
	"Loglinear Analysis",
	"Main Effect",
	"Margin of Error",
	"Markov Chain",
	"Matched pairs",
	"Maximum Likelihood",
	"MDS",
	"Mean",
	"Measurement Error",
	"Median",
	"Meta-Analysis",
	"Micro-Ethnography",
	"Missing Completely at Random",
	"Missing Data",
	"Misspecification",
	"Mixed Method",
	"Mode",
	"Monotonic Trend",
	"Monte Carlo",
	"Multicollinearity",
	"Multidimensional",
	"Multifactor",
	"Multinomial",
	"Multivariate",
	"Mutually Exclusive",
	"Narrative Research",
	"Natural Experiment",
	"Naturalistic Observation",
	"Negative Association",
	"Nominal",
	"Nonlinear",
	"Nonparametric",
	"Nonresponse Error",
	"Nonsampling Error",
	"Nonsignificant",
	"Norm",
	"Observed Value",
	"Open Question",
	"Order Effect",
	"Ordinal",
	"Outlier",
	"Oversampling",
	"Overt Observation",
	"P Value",
	"Paired Comparison",
	"Panel Study",
	"Participant Observation",
	"PASTA Analysis",
	"Path Analysis",
	"PCA",
	"Percentile",
	"Phenomenology",
	"Pilot Study",
	"Point Estimate",
	"Positively Associated",
	"Power",
	"Precision",
	"Presumptive Consent",
	"Pretest",
	"Primary data",
	"Principal Component Analysis",
	"Probability",
	"Probit Model",
	"Psychometric Property",
	"Q Methodology",
	"Qualitative",
	"Quantile",
	"Quantitative",
	"Quartile",
	"Quasiexperiment",
	"Quasiexperimental",
	"Questionnaire",
	"R Squared",
	"Random Effects Model",
	"Random Error",
	"Random Selection",
	"Randomization",
	"Range",
	"Rank Order",
	"Rate",
	"Rating Scale",
	"Ratio",
	"Regression",
	"Repeated Measures",
	"Replicability",
	"Representativeness",
	"Respondent",
	"Response Categories",
	"Retrospective Consent",
	"Retrospective Look",
	"Rigorous Research",
	"Robustness",
	"Sample",
	"Sampling",
	"Scaled Score",
	"Scatter Plot",
	"Scattergram",
	"Scatterplot",
	"Scenario Analysis",
	"Scenario Planning",
	"Secondary Data",
	"Selective Observation",
	"Semantic Differential Scale",
	"Sensitivity Analysis",
	"Sign Test",
	"Significance",
	"Simulation",
	"Single Blind",
	"Skewness",
	"Slope",
	"Social Desirability",
	"Social Network",
	"Sociogram",
	"Spurious Relationship",
	"Standard Error",
	"Standardization",
	"Standardized",
	"Statistic",
	"Statistical",
	"Stratification",
	"Structural Equation Modeling",
	"Structural Model",
	"Structured Observation",
	"Subsample",
	"Survey Research",
	"T Test",
	"Test-Retest Reliability",
	"Thematic Analysis",
	"Time Series",
	"Time Variant",
	"Time-Invariant",
	"Treatment Effect",
	"Treatment offered",
	"Treatment on the Treated",
	"Triangulation",
	"Two-Tailed",
	"Type 1 Error",
	"Type 2 Error",
	"Type I Error",
	"Type II Error",
	"Typology",
	"Unbiased",
	"Unconditional Longitudinal Model",
	"Unconditional Longitudinal Study",
	"Undersampling",
	"Unfolding Question",
	"Unit of Analysis",
	"Univariate",
	"Unstructured Observation",
	"Validity",
	"Variable",
	"Variance",
	"Weighted Score",
	"Weighting",
	"xij",
	"yij",
	"Z Score",
	"Z Test",
}

// qualitativeMarkers and quantitativeMarkers are OURS, not the paper's.
//
// The published method never labels a term as leaning one way. It feeds all
// counts to a trained XGBoost model and lets the model learn the weights.
// These two lists exist so a lean can be computed with NO model at all, which
// keeps this package deterministic and dependency-free.
//
// They were chosen a priori from the methods literature and only then checked
// against six papers, which is the right order: picking the terms that happen
// to separate a small sample would be fitting to it and would tell us nothing.
// No term appears in both lists, and TestMarkersAreDisjoint asserts it.
var qualitativeMarkers = []string{
	"Qualitative",
	"Interview",
	"In-depth Interviewing",
	"Focus Group",
	"Thematic Analysis",
	"Grounded Theory",
	"Ethnography",
	"Micro-Ethnography",
	"Ethnographic Decision Model",
	"Case Study",
	"Phenomenology",
	"Content Analysis",
	"Narrative Research",
	"Participant Observation",
	"Naturalistic Observation",
	"Covert Observation",
	"Overt Observation",
	"Unstructured Observation",
	"Triangulation",
	"Insiderness",
	"Cognitive Interviewing",
	"Focus Study",
	"Critical Incident Technique",
	"Q Methodology",
	"Open Question",
	"Delphi",
	"Expert Panel",
	"Expert study",
}

// See qualitativeMarkers.
var quantitativeMarkers = []string{
	"Quantitative",
	"Variable",
	"Variance",
	"Regression",
	"Coefficient",
	"Likert Scale",
	"ANOVA",
	"ANCOVA",
	"Chi Square",
	"Chi Squared",
	"T Test",
	"Z Test",
	"Z Score",
	"Cronbach’s Alpha",
	"Standard Error",
	"P Value",
	"Correlation",
	"Correlational",
	"Factor Analysis",
	"Structural Equation Modeling",
	"Principal Component Analysis",
	"Composite Reliability",
	"Effect Size",
	"Statistic",
	"Statistical",
	"Standardized",
	"Standardization",
	"Confidence",
	"Discriminant Analysis",
	"Cluster Analysis",
	"Multicollinearity",
	"Heteroskedastic",
	"Probit Model",
	"Logit Model",
	"Log-Linear Analysis",
	"Loglinear Analysis",
	"Maximum Likelihood",
	"Least Squares",
	"Monte Carlo",
	"Bootstrapping",
	"Kruskal Wallis Test",
	"Friedman Test",
	"Sign Test",
	"Skewness",
	"Kurtosis",
	"Percentile",
	"Quartile",
	"Quantile",
	"Median",
	"Mean",
	"Mode",
	"Degrees of Freedom",
	"R Squared",
	"Random Effects Model",
	"Hierarchical Linear Modeling",
	"Generalized Linear Model",
	"Generalized Linear Mixed Model",
	"Multivariate",
	"Univariate",
	"Multinomial",
	"Path Analysis",
	"Sensitivity Analysis",
	"Type 1 Error",
	"Type 2 Error",
	"Type I Error",
	"Type II Error",
}

// mixedMarkers is a single term, and it is the paper's own.
//
// "Mixed Method" is already in the 301, which is the useful accident here: the
// authors trained a BINARY classifier and had no mixed class, yet the
// vocabulary for one was in their glossary all along. On the six test papers it
// occurs only in the two mixed-methods ones.
//
// It is a FLAG rather than a third score. A paper that merely discusses mixed
// methods would trip it, so it marks a paper as worth a human's attention
// rather than deciding anything.
var mixedMarkers = []string{
	"Mixed Method",
}
