package segment

// roleKeywords is the role table's keyword set, transcribed from
// section_roles[*].keywords in step3_table_v2.3.json.
//
// 157 keywords across 16 roles, and no keyword appears under two roles — a
// property TestRoleTableMatchesTable asserts, because the matching rule in §6
// step 5 counts DISTINCT ROLES rather than keyword hits, and a keyword owned by
// two roles would make a single hit ambiguous on its own.
//
// The table is held in Go rather than parsed from JSON at run time for the same
// reason as the container lists in container.go: this package is pure domain
// logic and must stay callable with no working directory and no file access.
// The duplication is made safe by a test that compares the two, not by care.
//
// The keyword set is ORDER-INSENSITIVE. Matching iterates a map and then sorts
// its results, so nothing here depends on the sequence below.
var roleKeywords = map[Role][]string{
	RoleAbstract: {
		"abstract",
		"summary",
	},
	RoleIntroduction: {
		"introduction",
		"background",
		"overview",
	},
	RoleLiteratureReview: {
		"literature review",
		"related work",
		"related literature",
		"prior research",
		"prior literature",
		"review of literature",
		"background literature",
		"state of the art",
		"extant literature",
	},
	RoleTheory: {
		"theoretical framework",
		"theoretical background",
		"conceptual framework",
		"theory development",
		"theory and hypotheses",
		"hypothesis development",
		"hypotheses development",
		"conceptual model",
		"research model",
		"theoretical foundations",
	},
	RoleMethodology: {
		"method",
		"methods",
		"methodology",
		"research design",
		"research methodology",
		"empirical strategy",
		"empirical approach",
		"analytic approach",
		"estimation strategy",
		"materials and methods",
		"study design",
		"data and methods",
		"data and method",
		"sample",
		"sampling",
		"participants",
		"respondents",
		"data collection",
		"data source",
		"data sources",
		"study sample",
		"sample and data",
		"sample characteristics",
		"population and sample",
		"measures",
		"measurement",
		"measurement model",
		"operationalization",
		"operationalisation",
		"variables",
		// Singular too. The plural alone resolved "4.3 Independent variables" and
		// "4.4 Control variables" while leaving "4.2 Dependent variable" unmatched
		// in the same paper — one letter apart, and the reviewer got a question
		// about a heading whose siblings had answered themselves.
		"variable",
		"instrument",
		"instruments",
		"survey instrument",
		"construct measurement",
		"procedure",
		"procedures",
		"data collection procedure",
		"case description",
		"research setting",
		"empirical setting",
		"study context",
		"case study context",
		"site description",
		"field setting",
		"manipulation check",
		"manipulation checks",
		"construct validity",
		"discriminant validity",
		"convergent validity",
		"reliability analysis",
		"model specification",
		"hypothesis testing",
	},
	RoleResults: {
		"results",
		"empirical results",
		"findings",
		"analysis and results",
		"descriptive statistics",
		"results and analysis",
		"empirical findings",
		"quantitative results",
		"additional analyses",
		"supplementary analyses",
		"post hoc analysis",
		"post hoc analyses",
		"robustness checks",
		"robustness check",
		"robustness tests",
		"sensitivity analysis",
		"sensitivity analyses",
		"replication study",
		"replication analysis",
		"boundary conditions",
		"thematic findings",
		"case findings",
		"qualitative results",
	},
	RoleDiscussion: {
		"discussion",
		"general discussion",
		"discussion of results",
		"discussion and implications",
		"theoretical implications",
		"implications for theory",
		"contribution to theory",
		"practical implications",
		"implications for practice",
		"managerial implications",
		"implications for managers",
		"policy implications",
		"implications for policy",
	},
	RoleLimitations: {
		"limitations",
		"study limitations",
		"limitations of the study",
		"future research",
		"future research directions",
		"directions for future research",
		"avenues for future research",
	},
	RoleConclusion: {
		"conclusion",
		"conclusions",
		"concluding remarks",
		"summary and conclusion",
		"summary and conclusions",
		"final remarks",
	},
	RoleAcknowledgments: {
		"acknowledgments",
		"acknowledgements",
	},
	RoleFunding: {
		"funding",
		"funding statement",
		"financial support",
		"grant information",
	},
	RoleAuthorContributions: {
		"author contributions",
		"authors' contributions",
		"credit statement",
		"credit author statement",
		"credit authorship contribution statement",
	},
	RoleDataAvailability: {
		"data availability",
		"data availability statement",
		"availability of data",
	},
	RoleEthicsStatement: {
		"ethics statement",
		"ethical approval",
		"irb approval",
		"institutional review board",
		"research ethics",
		"informed consent",
	},
	RoleConflictOfInterest: {
		"conflict of interest",
		"conflicts of interest",
		"competing interests",
		"competing interest",
		"declaration of interest",
		"declaration of competing interest",
		"declaration of competing interests",
	},
	RoleReferences: {
		"references",
		"bibliography",
		"works cited",
		"reference list",
	},
}
